name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The new version"
        type: "string"
        required: true
      prerelease:
        description: "Whether this release is considered a prerelease"
        type: "boolean"
        default: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
        # Give the default GITHUB_TOKEN write permission to commit and push the
        # added or changed files to the repository.
        contents: write
    steps:
      # checkout the repo
      - uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}
      # install rust tooling
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Change Version
        run: ./bump-version.sh ${{ inputs.version }}
      # commit version bump
      - name: Debug
        run: echo "${{ inputs.version }}"
      - name: Commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            tagging_message: ${{ inputs.version }}
      - name: Build Release Binary
        run: cargo build --release
      - name: Zip Executable
        run: |
          zip --junk-paths markdown-cli ./target/release/markdown-cli
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ inputs.version }}
          draft: false
          body: |
            Release version ${{ inputs.version }}
          prerelease: ${{ inputs.prerelease }}
          artifacts: markdown-cli.zip
          artifactContentType: application/zip
          tag: ${{ inputs.version }}
          commit: ${{ steps.commit.outputs.commit_hash }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
