name: Release
on:
  workflow_dispatch:
    inputs:
      repo_token:
        description: "A personal access token with write permissions to the releases for this repo"
        type: "string"
        required: true
      release_type:
        description: "Release type (major, minor, patch"
        type: "string"
        required: false
        default: "patch"
      prerelease:
        description: "Whether this release is considered a prerelease"
        type: "boolean"
        default: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - uses: actions/checkout@v4
      # install rust tooling
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo Bump
        id: cargo_bump
        uses: tj-actions/cargo-bump@v3
        with:
          release_type: ${{ inputs.release_type }}
      - name: Build Release Binary
        run: cargo build --release
      - name: Zip Executable
        run: |
          zip --junk-paths markdown-cli ./target/release/markdown-cli
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.cargo_bump.outputs.new_version }}
          draft: false
          body: |
            Release version ${{ steps.cargo_bump.outputs.new_version }}
          prerelease: ${{ inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ inputs.repo_token }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ inputs.repo_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./markdown-cli.zip
          asset_name: markdown-cli.zip
          asset_content_type: application/zip
